### ISSUE TITLE
Update wireframe, refactored the tool

### ISSUE THREAD

**Issue by DylanMoriarty** [yourbodynotyourchoice/yourbodynotyourchoice.github.io#13]
Hey folks!

While going in to update the UI, I got really frustrated working with the old script, soooo I rewrote it.

Main advantages here are:

1) Easier to add new categories if we'd want
2) Better organization for things writing each section's analysis
3) Easier to make mobile friendly
4) Popup's that actually work!
5) Better integration of the CPC/Clinic bit

This was my quick idea for a easier interface:

![desktop hd](https://cloud.githubusercontent.com/assets/9341928/21080597/1794e964-bf81-11e6-97ee-59fc22d293f7.png)

Few changes: 
- Category buttons stay fixed on the left side, working as a better navigation for the site
- For the analysis section only the category you're currently viewing is shown
- CPC turns into it's own section vs. just being an overlay
- No more VCR controls. Default view is 2016, when you hit a play button it'll play through the years. Otherwise they could be viewable by hovering over the bar chart values.

![mobile portrait](https://cloud.githubusercontent.com/assets/9341928/21080529/65d0c79e-bf7f-11e6-8ffa-48b289aaee69.png)

For mobile we can drop a lot of the above bells & whistles and just make it a simple map for modern values & the analysis text.

@kkowalsky @tolomaps

**Comment by DylanMoriarty** [comment]
[Can be viewed here ](https://github.com/yourbodynotyourchoice/yourbodynotyourchoice.github.io/tree/refactor). I currently have the map hooked up to data, means of sorting data by year/category & have the analysis content switcher working.

**Comment by kkowalsky** [comment]
this is definitely a more effective retooling, :+1: Dylan.

**Comment by tolomaps** [comment]
@DylanMoriarty you are awesome for refactoring!

Buuut I couldn't get it to run locally...
`npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robin/Documents/yourbodynotyourchoice.github.io/npm-debug.log`

Thoughts?

**Comment by DylanMoriarty** [comment]
@tolomaps: Ah, just missing the npm-debug.log file. I must have added it locally without removing it from the gitignore. Fixin'

**Comment by DylanMoriarty** [comment]
If you click the little green box the map currently plays through the years from 1973 to 2013. 

Haven't quite gotten around to actually finishing it though, so it starts to break if you click it multiple times or click into a different category.

Laundry List of things still to do:

- [ ] Finish map temporal functionality
- [ ] Add layer for CPC/Abortion Clinics, & toggle feature to go along.
- [ ] Add in bar chart
- [ ] Add little hover-popup for citations - [(like this I'm thinkin')](https://dylanmoriarty.github.io/blog/moriarty-hand.html)
- [ ] Style the thing
- [ ] Mobile friendly it up

**Comment by tolomaps** [comment]
Bah I still can't get it to work. Am getting this:

```
> yourbody(not)yourchoice@1.0.0 serve /Users/robin/Documents/yourbodynotyourchoice.github.io
> DS_ENV=development gulp collecticons && gulp serve

[00:59:51] Using gulpfile ~/Documents/yourbodynotyourchoice.github.io/gulpfile.js
[00:59:51] Starting 'collecticons'...
[00:59:52] gulp-svgicons2svgfont: Font created
[00:59:52] Finished 'collecticons' after 1.05 s
[00:59:53] Using gulpfile ~/Documents/yourbodynotyourchoice.github.io/gulpfile.js
[00:59:53] Starting 'vendorScripts'...
[00:59:53] Starting 'javascript'...
[00:59:53] Starting 'styles'...
[00:59:53] Starting 'fonts'...
[00:59:53] Finished 'fonts' after 8.85 ms
[00:59:53] Finished 'styles' after 208 ms

/Users/robin/Documents/yourbodynotyourchoice.github.io/node_modules/buble/dist/buble.umd.js:3706
  exports.REGULAR = new Map([
                        ^
ReferenceError: Map is not defined
    at /Users/robin/Documents/yourbodynotyourchoice.github.io/node_modules/buble/dist/buble.umd.js:3706:25
    at __commonjs (/Users/robin/Documents/yourbodynotyourchoice.github.io/node_modules/buble/dist/buble.umd.js:11:70)
    at /Users/robin/Documents/yourbodynotyourchoice.github.io/node_modules/buble/dist/buble.umd.js:3700:34
    at acorn (/Users/robin/Documents/yourbodynotyourchoice.github.io/node_modules/buble/dist/buble.umd.js:2:66)
    at Object.<anonymous> (/Users/robin/Documents/yourbodynotyourchoice.github.io/node_modules/buble/dist/buble.umd.js:5:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v0.10.33
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! yourbody(not)yourchoice@1.0.0 serve: `DS_ENV=development gulp collecticons && gulp serve`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the yourbody(not)yourchoice@1.0.0 serve script 'DS_ENV=development gulp collecticons && gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yourbody(not)yourchoice package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DS_ENV=development gulp collecticons && gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yourbody(not)yourchoice
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yourbody(not)yourchoice
npm ERR! There is likely additional logging output above.
```

**Comment by DylanMoriarty** [comment]
Well that's no fun. @tolomaps what version of npm are you using? [Try it with v4.6.2.](http://www.jasonfleetwoodboldt.com/writing/2014/06/25/how-to-install-old-versions-of-node-and-npm/)
